apiVersion: v1
kind: Namespace
metadata:
  name: sre-bootcamp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sre-bootcamp
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        proxy_pass http://backend;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: sre-bootcamp
data:
  password: c2VjcmV0Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sre-bootcamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sre-bootcamp
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
