apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # The email-password will be added by the fix-notifications.sh script
  # DO NOT add sensitive credentials here as this file is committed to git
