{{- if .Values.blackboxExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blackboxExporter.service.name | default .Values.blackboxExporter.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.blackboxExporter.name }}
  annotations:
    {{- with .Values.blackboxExporter.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.blackboxExporter.service.type }}
  ports:
    - port: {{ .Values.blackboxExporter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.blackboxExporter.name }}
{{- end }}
