{{- if and .Values.blackboxExporter.enabled .Values.blackboxExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.blackboxExporter.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.blackboxExporter.name }}
{{- end }}
