apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream backend {
        server {{ include "student-api.fullname" . }}:{{ .Values.studentApi.service.port }};
      }
      server {
        listen 80;
        server_name localhost;

        location / {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
