{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.forceEmptyDir) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.persistence.name | default (printf "%s-data" .Release.Name) }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
    app: postgres
    release: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: delete
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.persistence.storageClass }}
  {{- if (eq "-" .Values.postgres.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
