apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studentApi.service.type }}
  ports:
    - port: {{ .Values.studentApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "student-api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
{{- if .Values.nginx.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
{{- end }}
