apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_LOG_LEVEL
              value: "debug"
            - name: GF_LOG_MODE
              value: "console"
