apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-config
  namespace: observability
data:
  alerting.yaml: |
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['alertname', 'job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'slack-notifications'
        receivers:
          - name: 'slack-notifications'
            slack_configs:
            - api_url_file: /etc/secrets/slack/webhook-url
              channel: '#alerts'
              title: '{{ template "slack.default.title" . }}'
              text: '{{ template "slack.default.text" . }}'
              send_resolved: true
