apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: student-api
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvc3R1ZGVudHNkYj9zc2xtb2RlPWRpc2FibGU=
