# Production environment values
namespace:
  create: true
  name: "prod-student-api"

studentApi:
  image:
    repository: ketankarki/student-api
    tag: latest
    pullPolicy: Always
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 8080

postgres:
  image:
    repository: postgres
    tag: 15.3
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  database:
    name: api
    user: postgres
    password: postgres  # In production, use a secret manager or Kubernetes secrets

nginx:
  configMap:
    name: nginx-config
    enabled: true
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
