apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ketan-Karki/sre-student-api
    targetRevision: main
    path: helm-charts/student-api-helm
    helm:
      valueFiles:
        - environments/prod/values.yaml
      parameters:
        # Fix namespace to match destination
        - name: namespace.name
          value: student-api
        # Fix image tags for containers
        - name: studentApi.image.tag
          value: latest
        - name: postgres.image.tag
          value: 15.3-alpine
        - name: nginx.image.tag
          value: stable-alpine
        # Configure nginx
        - name: nginx.configMap.name
          value: nginx-config
  destination:
    server: https://kubernetes.default.svc
    namespace: student-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
