apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Project roles
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, create, */*, allow
    p, role:developer, applications, update, */*, allow
    p, role:developer, applications, delete, */*, deny
    p, role:developer, logs, get, */*, allow
    p, role:developer, exec, create, */*, allow
    
    # Admin role has all permissions
    p, role:admin, *, *, */*, allow
    
    # Assign roles to users
    g, ketankarki2626@gmail.com, role:admin
    g, ketankarki2626, role:developer
  scopes: '[groups, name]'
