apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Ketan-Karki/sre-student-api
  username: your-github-username
  password: your-github-personal-access-token
