apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - applicationset.yaml
  - argocd-cm.yaml
  - argocd-notifications-cm.yaml
  - argocd-rbac-cm.yaml
  - repository-secret.yaml
  - discord-webhook-secret.yaml

namespace: argocd

secretGenerator:
- name: discord-webhook-secret
  namespace: argocd
  envs:
  - discord-webhook.env  # This file should NOT be committed to git
