apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Ketan-Karki/sre-student-api
  # These will be replaced by the script when applying
  username: ${GIT_USERNAME}
  password: ${GIT_PASSWORD}
