apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api
  labels: # Add service labels
    app: postgres
    tier: database
spec:
  selector:
    app: postgres
  ports:
    - name: postgresql # Add descriptive port name
      protocol: TCP
      port: 5432
      targetPort: 5432
