apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done;",
            ]
      containers:
        - name: student-api
          image: ketan-karki/student-api:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: student-api-config
            - secretRef:
                name: postgres-secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
