apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
  namespace: student-api
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Metrics endpoint
        location /metrics {
            alias /usr/share/nginx/html/metrics/;
            default_type text/plain;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
