apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
    - name: http-api        # Add descriptive port name
      protocol: TCP         # Explicitly specify protocol
      port: 8080
      targetPort: 8080
  type: ClusterIP
