apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
  labels:
    app.kubernetes.io/name: student-api
spec:
  selector:
    app.kubernetes.io/name: student-api
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8080
      targetPort: 8080
      name: metrics
