apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: observability
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30100
  type: NodePort
