# Values for student-api chart in development environment
namespace:
  create: true
  name: dev-student-api

studentApi:
  image:
    repository: student-api
    tag: latest
    pullPolicy: Never # Use Never for local images
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080
  # Add health checks for better pod lifecycle management
  livenessProbe:
    httpGet:
      path: /api/v1/healthcheck
      port: 8080
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /api/v1/healthcheck
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 10

postgres:
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  database:
    name: api
    user: postgres
    password: postgres
  persistence:
    enabled: true
    size: 1Gi

nginx:
  enabled: true
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
