# Values for student-api chart in development environment
namespace:
  create: true
  name: dev-student-api

studentApi:
  replicaCount: 1
  image:
    repository: us-west1-docker.pkg.dev/sreworkshop/student-api
    tag: latest
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    normal:
      - name: ENV_TYPE
        value: "development"
      - name: LOG_LEVEL
        value: "debug"
    secret:
      - name: DB_HOST
        value: "mongodb-dev:27017"
      - name: DB_NAME
        value: "students-dev"

postgres:
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  database:
    name: api
    user: postgres
    password: postgres
  persistence:
    enabled: true
    size: 1Gi

nginx:
  enabled: true
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
