# Development environment values
namespace:
  create: true
  name: "dev-student-api"

studentApi:
  image:
    repository: ketan-karki/student-api
    tag: 15cde29
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080

postgres:
  image:
    repository: postgres
    tag: 15cde29
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  database:
    name: api
    user: postgres
    password: postgres

nginx:
  enabled: true
  image:
    repository: nginx
    tag: 15cde29
    pullPolicy: IfNotPresent
  replicas: 1
