# Values for student-api chart in development environment
namespace:
  create: true
  name: dev-student-api

studentApi:
  image:
    repository: student-api
    tag: 5506bee
    pullPolicy: Never  # Use Never for local images
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080

postgres:
  image:
    repository: postgres
    tag: 5506bee
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  database:
    name: api
    user: postgres
    password: postgres
  persistence:
    enabled: true
    size: 1Gi

nginx:
  enabled: true
  image:
    repository: nginx
    tag: 5506bee
    pullPolicy: IfNotPresent
  replicas: 1
