# Global settings
nameOverride: ""
fullnameOverride: ""

# Image credentials for private registry access
imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""
  # Set to true to create a Secret for pulling images from private registries
  createSecret: false
  secretName: "registry-credentials"

# Namespace configuration
namespace:
  create: true
  name: "student-api"

# Student API configuration
studentApi:
  image:
    repository: ketan-karki/student-api
    tag: 66779b1
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: 66779b1
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 1Gi
  
  # Database credentials
  database:
    name: api
    user: postgres
    password: postgres

# NGINX configuration
nginx:
  enabled: true
  image:
    repository: nginx
    tag: 66779b1
    pullPolicy: IfNotPresent
  replicas: 1
  configMap:
    name: nginx-config
  service:
    type: LoadBalancer
    port: 80
