name: Container Image CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - '*.go'
      - 'middleware/**'
      - 'models/**'
      - 'routes/**'
      - 'migrations/**'
      - 'db/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'go.mod'
      - 'go.sum'
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - master
    paths:
      - '*.go'
      - 'middleware/**'
      - 'models/**'
      - 'routes/**'
      - 'migrations/**'
      - 'db/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'go.mod'
      - 'go.sum'
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE: ketankarki/student-api
  GO_VERSION: "1.21"

jobs:
  build-and-test:
    name: Build, Test, and Lint
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build API
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Install and run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m --out-format=colored-line-number
          skip-pkg-cache: true
          skip-build-cache: true

  docker:
    name: Build and Push Container Images
    needs: build-and-test
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push container images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
