name: Update Helm Values

on:
  workflow_run:
    workflows: ["Container Image CI"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  update-helm-values:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest image tag
        id: get-tag
        run: |
          # Extract the SHA from the successful workflow
          SHA=${{ github.event.workflow_run.head_sha }}
          SHORT_SHA=${SHA::7}

          # Set the image tag based on whether this is a tag or commit
          if [[ "${{ github.event.workflow_run.head_branch }}" =~ ^refs/tags/v ]]; then
            # If this was triggered by a tag, use the tag as the image version
            TAG_NAME="${{ github.event.workflow_run.head_branch }}"
            TAG_NAME="${TAG_NAME#refs/tags/}"
            echo "IMAGE_TAG=${TAG_NAME}" >> $GITHUB_ENV
            echo "UPDATE_ENV=prod" >> $GITHUB_ENV
            echo "Detected tag: ${TAG_NAME}"
          else
            # Use the commit SHA for non-tag builds
            echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
            echo "UPDATE_ENV=dev" >> $GITHUB_ENV
            echo "Using commit SHA: ${SHORT_SHA}"
          fi

      - name: Update Helm values
        run: |
          # Update the image tag in the main values.yaml
          sed -i "s/tag: .*$/tag: ${{ env.IMAGE_TAG }}/g" helm-charts/student-api-helm/values.yaml

          # Update environment-specific values files
          for env in dev prod; do
            VALUES_FILE="helm-charts/student-api-helm/environments/${env}/values.yaml"
            if [ -f "$VALUES_FILE" ] && [ "$env" = "${{ env.UPDATE_ENV }}" ]; then
              sed -i "s/tag: .*$/tag: ${{ env.IMAGE_TAG }}/g" "$VALUES_FILE"
              echo "Updated ${env} environment values file"
            fi
          done

      - name: Verify changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in Helm values files"
            git diff
          else
            echo "No changes to commit"
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add helm-charts/student-api-helm/values.yaml
          git add helm-charts/student-api-helm/environments/*/values.yaml || true

          git commit -m "Update image tag to ${{ env.IMAGE_TAG }} for ${{ env.UPDATE_ENV }} environment [skip ci]" || true
          git push
